// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```




// ...



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmGlswHt_Hgl5dS6EnNTb5qggYSl0WiQQ',
    appId: '1:1046504720649:web:da52537b0d9c05c8276bd8',
    messagingSenderId: '1046504720649',
    projectId: 'allergyhelperprojectd',
    authDomain: 'allergyhelperprojectd.firebaseapp.com',
    storageBucket: 'allergyhelperprojectd.appspot.com',
    measurementId: 'G-ESRM2RTNDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm6_KSOfpN3dCCrpWGaiainiJ2HLUXvZQ',
    appId: '1:1046504720649:android:4cad8d00ae48d52a276bd8',
    messagingSenderId: '1046504720649',
    projectId: 'allergyhelperprojectd',
    storageBucket: 'allergyhelperprojectd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdF3FZrbSxUOzLyOeJxL-xktm1GImRsBk',
    appId: '1:1046504720649:ios:223081bd2b763d80276bd8',
    messagingSenderId: '1046504720649',
    projectId: 'allergyhelperprojectd',
    storageBucket: 'allergyhelperprojectd.appspot.com',
    iosBundleId: 'com.example.allergyHelperProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdF3FZrbSxUOzLyOeJxL-xktm1GImRsBk',
    appId: '1:1046504720649:ios:223081bd2b763d80276bd8',
    messagingSenderId: '1046504720649',
    projectId: 'allergyhelperprojectd',
    storageBucket: 'allergyhelperprojectd.appspot.com',
    iosBundleId: 'com.example.allergyHelperProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmGlswHt_Hgl5dS6EnNTb5qggYSl0WiQQ',
    appId: '1:1046504720649:web:cde5e2a68fa678cb276bd8',
    messagingSenderId: '1046504720649',
    projectId: 'allergyhelperprojectd',
    authDomain: 'allergyhelperprojectd.firebaseapp.com',
    storageBucket: 'allergyhelperprojectd.appspot.com',
    measurementId: 'G-KYG5N0BH0X',
  );
}
